version: '3'
services:  
  redis:
    container_name: redis
    image: docker.io/bitnami/redis:latest
    ports:
    - "6379:6379"
    # volumes:
    # - /data/redis:/bitnami/redis/data
    env_file:
    - .env
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - /data/postgres:/data/postgres
    env_file:
    - .env
  rabbitmq:
    image: rabbitmq:3
    ports: 
      - 5672:5672
    env_file:
    - .env  